In [ ]:
pip install numpy


In [ ]:
import numpy as np

# Q-learning parameters
learning_rate = 0.1
discount_factor = 0.9
num_states = 10  # Speed levels
num_actions = 3  # Accelerate, Decelerate, Maintain
q_table = np.zeros((num_states, num_actions))

def choose_action(state):
    return np.argmax(q_table[state])

# Simulating training
for episode in range(1000):
    state = np.random.randint(0, num_states)
    action = choose_action(state)
    next_state = max(0, min(num_states - 1, state + action - 1))
    reward = -1 if next_state < 5 else 1  # Sample reward logic
    q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_factor * np.max(q_table[next_state]) - q_table[state, action])

print("Trained Q-Table:", q_table)


Trained Q-Table: [[-1.48542229 -1.48542229 -0.11486448]
 [-1.15074913 -1.13615128  1.24713731]
 [-0.49129723 -0.4900995   2.81071577]
 [-0.28       -0.29701     4.70680295]
 [-0.1        -0.1         6.71781463]
 [-0.1         6.51906886  0.        ]
 [ 6.61642387  0.          0.        ]
 [ 6.53891564  0.          0.        ]
 [ 6.26855641  0.          0.        ]
 [ 6.3879767   0.          0.        ]]


In [ ]:


import numpy as np
import pandas as pd

# Sample data (replace with your actual data)
data = {'speed': [30, 40, 50, 60, 70, 80, 90, 100],
        'distance': [100, 80, 60, 40, 20, 10, 5, 2]}  # Example distances
df = pd.DataFrame(data)


# Q-learning parameters (adjust as needed)
learning_rate = 0.1
discount_factor = 0.9
num_states = 10  # Discretize speed (adjust based on data range)
num_actions = 3  # Accelerate, decelerate, maintain
q_table = np.zeros((num_states, num_actions))


def discretize_speed(speed):
  # Discretize speed into states (adjust ranges based on your data)
  if speed < 30: return 0
  elif speed < 40: return 1
  elif speed < 50: return 2
  elif speed < 60: return 3
  elif speed < 70: return 4
  elif speed < 80: return 5
  elif speed < 90: return 6
  elif speed < 100: return 7
  else: return 9 # Cap at max speed


def choose_action(state):
  return np.argmax(q_table[state])


# Training loop (adjust based on your data)
for _ in range(1000): # Training episodes
  current_speed = np.random.choice(df['speed'])
  current_state = discretize_speed(current_speed)
  current_distance = df[df['speed'] == current_speed]['distance'].iloc[0]

  action = choose_action(current_state)

  # Simulate speed change based on action
  if action == 0:  # Accelerate
      new_speed = min(100, current_speed + 5) # Limit maximum speed
  elif action == 1:  # Decelerate
      new_speed = max(30, current_speed - 5) # Limit minimum speed
  else: #Maintain
      new_speed = current_speed

  next_state = discretize_speed(new_speed)

  # Reward function (consider distance, speed limit, etc.)
  reward = 0
  if current_distance > 0:
    reward = - (current_distance - 5)/10 + (new_speed/50) # Sample reward (adjust based on needs)

  q_table[current_state, action] = q_table[current_state, action] + learning_rate * (reward + discount_factor * np.max(q_table[next_state]) - q_table[current_state, action])

# Prediction
current_speed = 60
current_state = discretize_speed(current_speed)
predicted_action = choose_action(current_state)


if predicted_action == 0:
    print("Recommended Action: Accelerate")
elif predicted_action == 1:
    print("Recommended Action: Decelerate")
else:
    print("Recommended Action: Maintain Speed")

Recommended Action: Accelerate
